# .goreleaser.yml
# Build customization
builds:
  - main: waflyctl.go
    binary: waflyctl
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
archive:
  format: tar.gz
  files:
    - waflyctl.toml
    - config_examples/waflyctl.fastly_soc_example.toml 
    - README.md
