language: go

go:
  - 1.13.x

before_script:
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck

script:
  - go mod verify
  - go vet 
  - staticcheck -fail=-U1000
  - golint -set_exit_status

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
